export const dataSeven = [
  {
    id: 1,
    titre: "One Piece",
    auteur: "Eiichiro Oda",
    description: "Luffy parcourt les mers pour devenir le Roi des Pirates.",
    description_longue: "Monkey D. Luffy et son équipage voyagent à travers un vaste monde rempli d'îles exotiques, d'alliés inoubliables et d'ennemis redoutables en quête du trésor légendaire One Piece.",
    image: "https://i.pinimg.com/1200x/b7/36/2c/b7362cd4088205d4a71b062538e5b346.jpg",
    iconImage: "https://cdn.myanimelist.net/images/characters/2/200001.jpg",
    chapitres: "1100+",
    date: "1997-07-22",
    statut: "En cours",
    lien: "/one-piece",
    type: "Anime",
    genre: ["Aventure", "Action", "Comédie", "Fantasy", "Pirates", "Amitié", "Épopée"]
  },
  {
    id: 2,
    titre: "Naruto",
    auteur: "Masashi Kishimoto",
    description: "Naruto rêve de devenir Hokage et de gagner le respect de son village.",
    description_longue: "Orphelin rejeté par son village, Naruto Uzumaki affronte de nombreuses épreuves pour maîtriser son pouvoir et prouver sa valeur, nouant des liens forts en chemin.",
    image: "https://cdn.myanimelist.net/images/anime/3/100002.jpg",
    iconImage: "https://cdn.myanimelist.net/images/characters/3/200002.jpg",
    chapitres: "700",
    date: "1999-09-21",
    statut: "Terminé",
    lien: "/naruto",
    type: "Anime",
    genre: ["Action", "Aventure", "Arts martiaux", "Drame", "Shonen", "Ninja", "Amitié"]
  },
  {
    id: 3,
    titre: "Bleach",
    auteur: "Tite Kubo",
    description: "Ichigo devient Shinigami pour protéger les vivants et les morts.",
    description_longue: "En héritant des pouvoirs d'une Shinigami, Ichigo Kurosaki affronte des menaces spirituelles et découvre sa place entre le monde des vivants et celui des esprits.",
    image: "https://cdn.myanimelist.net/images/anime/4/100003.jpg",
    iconImage: "https://cdn.myanimelist.net/images/characters/4/200003.jpg",
    chapitres: "686",
    date: "2001-08-07",
    statut: "Terminé",
    lien: "/bleach",
    type: "Anime",
    genre: ["Action", "Surnaturel", "Aventure", "Fantastique", "Shinigami", "Combat", "Mystère"]
  },
  {
    id: 4,
    titre: "Fullmetal Alchemist",
    auteur: "Hiromu Arakawa",
    description: "Deux frères alchimistes cherchent la pierre philosophale pour récupérer leurs corps.",
    description_longue: "Edward et Alphonse Elric ont payé le prix ultime pour une transmutation interdite. Leur quête de rédemption les mène dans un monde de complots militaires, d'homonculus et de vérités douloureuses sur l'alchimie.",
    image: "https://cdn.myanimelist.net/images/anime/5/100004.jpg",
    iconImage: "https://cdn.myanimelist.net/images/characters/5/200004.jpg",
    chapitres: "108",
    date: "2001-07-12",
    statut: "Terminé",
    lien: "/fullmetal-alchemist",
    type: "Anime",
    genre: ["Aventure", "Drame", "Fantasy", "Action", "Fraternité", "Philosophie", "Guerre"]
  },
  {
    id: 5,
    titre: "Death Note",
    auteur: "Tsugumi Ohba",
    description: "Un cahier mystérieux permet de tuer en écrivant des noms.",
    description_longue: "Light Yagami tente d'instaurer une justice absolue avec le Death Note, déclenchant un duel intellectuel mortel avec le détective L.",
    image: "https://cdn.myanimelist.net/images/anime/6/100005.jpg",
    iconImage: "https://cdn.myanimelist.net/images/characters/6/200005.jpg",
    chapitres: "108",
    date: "2003-12-01",
    statut: "Terminé",
    lien: "/death-note",
    type: "Anime",
    genre: ["Psychologique", "Thriller", "Surnaturel", "Mystère", "Drame", "Crime", "Intellectuel"]
  },
  {
    id: 6,
    titre: "Attack on Titan",
    auteur: "Hajime Isayama",
    description: "L'humanité combat des géants sans pitié pour sa survie.",
    description_longue: "Retranchés derrière d'immenses murs, des soldats et civils luttent contre la menace des Titans, découvrant au fil du récit des vérités sombres sur leur monde.",
    image: "https://cdn.myanimelist.net/images/anime/7/100006.jpg",
    iconImage: "https://cdn.myanimelist.net/images/characters/7/200006.jpg",
    chapitres: "139",
    date: "2009-09-09",
    statut: "Terminé",
    lien: "/attack-on-titan",
    type: "Anime",
    genre: ["Action", "Drame", "Dark Fantasy", "Mystère", "Post-apocalyptique", "Guerre", "Psychologique"]
  },
  {
    id: 7,
    titre: "Chainsaw Man",
    auteur: "Tatsuki Fujimoto",
    description: "Denji fusionne avec un démon pour devenir Chainsaw Man et survivre.",
    description_longue: "Dans un monde brutal, Denji se bat pour une vie simple, confronté à la violence, à l'amour et à sa propre humanité après sa transformation.",
    image: "https://cdn.myanimelist.net/images/anime/8/100007.jpg",
    iconImage: "https://cdn.myanimelist.net/images/characters/8/200007.jpg",
    chapitres: "140+",
    date: "2018-12-03",
    statut: "En cours",
    lien: "/chainsaw-man",
    type: "Anime",
    genre: ["Horreur", "Action", "Surnaturel", "Dark Fantasy", "Violence", "Drame", "Psychologique"]
  },
  {
    id: 8,
    titre: "Tokyo Ghoul",
    auteur: "Sui Ishida",
    description: "Un étudiant devient mi-humain, mi-goule après une rencontre fatale.",
    description_longue: "Ken Kaneki doit naviguer entre deux mondes après avoir été transformé en goule. Déchiré entre son humanité et ses nouveaux instincts, il cherche sa place dans une société qui le rejette.",
    image: "https://cdn.myanimelist.net/images/anime/9/100008.jpg",
    iconImage: "https://cdn.myanimelist.net/images/characters/9/200008.jpg",
    chapitres: "143",
    date: "2011-09-08",
    statut: "Terminé",
    lien: "/tokyo-ghoul",
    type: "Anime",
    genre: ["Horreur", "Surnaturel", "Drame", "Psychologique", "Dark Fantasy", "Identité", "Action"]
  },
  {
    id: 9,
    titre: "Hunter x Hunter",
    auteur: "Yoshihiro Togashi",
    description: "Gon part à la recherche de son père en devenant Hunter.",
    description_longue: "Gon Freecss découvre que son père disparu est un Hunter légendaire. En passant l'examen Hunter, il rencontre des alliés et ennemis dans un monde où le Nen révèle le vrai pouvoir.",
    image: "https://cdn.myanimelist.net/images/anime/10/100009.jpg",
    iconImage: "https://cdn.myanimelist.net/images/characters/10/200009.jpg",
    chapitres: "390+",
    date: "1998-03-16",
    statut: "En pause",
    lien: "/hunter-x-hunter",
    type: "Anime",
    genre: ["Aventure", "Action", "Fantasy", "Drame", "Tournoi", "Shonen", "Amitié"]
  },
  {
    id: 10,
    titre: "Demon Slayer: Kimetsu no Yaiba",
    auteur: "Koyoharu Gotouge",
    description: "Tanjiro devient pourfendeur de démons pour sauver sa sœur.",
    description_longue: "Après le massacre de sa famille par des démons, Tanjiro Kamado s'entraîne pour devenir pourfendeur de démons et trouver un moyen de redonner son humanité à sa sœur Nezuko.",
    image: "https://cdn.myanimelist.net/images/anime/11/100010.jpg",
    iconImage: "https://cdn.myanimelist.net/images/characters/11/200010.jpg",
    chapitres: "205",
    date: "2016-02-15",
    statut: "Terminé",
    lien: "/demon-slayer-kimetsu-no-yaiba",
    type: "Anime",
    genre: ["Action", "Aventure", "Dark Fantasy", "Drame", "Surnaturel", "Famille", "Démons"]
  },
 {
  id: 11,
  titre: "Jujutsu Kaisen",
  auteur: "Gege Akutami",
  description: "Yuji avale un doigt maudit et devient l'hôte d'un puissant démon.",
  description_longue: "Yuji Itadori rejoint l'école d'exorcisme pour contrôler Sukuna, le roi des fléaux. Entre combats spectaculaires et amitiés forgées, il découvre les sacrifices nécessaires pour protéger l'humanité.",
  image: "https://cdn.myanimelist.net/images/anime/12/100011.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/12/200011.jpg",
  chapitres: "250+",
  date: "2018-03-05",
  statut: "En cours",
  lien: "/jujutsu-kaisen",
  type: "Anime",
  genre: ["Action", "Surnaturel", "Dark Fantasy", "Exorcisme", "Drame", "Shonen", "Horreur"]
},
{
  id: 12,
  titre: "My Hero Academia",
  auteur: "Kohei Horikoshi",
  description: "Dans un monde de super-héros, Izuku rêve de devenir le plus grand.",
  description_longue: "Izuku Midoriya, né sans pouvoir dans une société où 80% de la population en possède, reçoit le don du plus grand héros. Son chemin vers la grandeur est pavé de dangers et de découvertes.",
  image: "https://cdn.myanimelist.net/images/anime/13/100012.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/13/200012.jpg",
  chapitres: "400+",
  date: "2014-07-07",
  statut: "En cours",
  lien: "/my-hero-academia",
  type: "Anime",
  genre: ["Action", "Super-héros", "Aventure", "Comédie", "École", "Science-fiction", "Shonen"]
},
{
  id: 13,
  titre: "Black Clover",
  auteur: "Yuki Tabata",
  description: "Asta, né sans magie, vise à devenir l'Empereur Mage.",
  description_longue: "Dans un royaume où la magie règne, Asta compense son absence de pouvoir par une détermination inébranlable et un grimoire anti-magie. Avec son rival Yuno, il gravit les échelons des Chevaliers Magiques.",
  image: "https://cdn.myanimelist.net/images/anime/14/100013.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/14/200013.jpg",
  chapitres: "370+",
  date: "2015-02-16",
  statut: "En cours",
  lien: "/black-clover",
  type: "Anime",
  genre: ["Action", "Aventure", "Fantasy", "Magie", "Shonen", "Rivalité", "Comédie"]
},
{
  id: 14,
  titre: "Fairy Tail",
  auteur: "Hiro Mashima",
  description: "Une guilde de mages vit des aventures magiques pleines d'action.",
  description_longue: "Natsu Dragneel et ses compagnons de la guilde Fairy Tail affrontent ennemis et mystères en quête de puissance et d'amitié. Un monde vibrant où la magie côtoie les liens indéfectibles.",
  image: "https://cdn.myanimelist.net/images/anime/15/100014.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/15/200014.jpg",
  chapitres: "545",
  date: "2006-08-02",
  statut: "Terminé",
  lien: "/fairy-tail",
  type: "Anime",
  genre: ["Aventure", "Fantasy", "Action", "Magie", "Comédie", "Amitié", "Shonen"]
},
{
  id: 15,
  titre: "Blue Lock",
  auteur: "Muneyuki Kaneshiro",
  description: "300 attaquants s'affrontent dans un programme radical pour créer le meilleur buteur.",
  description_longue: "Yoichi Isagi intègre Blue Lock, un projet controversé visant à former l'attaquant ultime du Japon. Dans cet environnement impitoyable, l'égoïsme devient la clé du succès.",
  image: "https://cdn.myanimelist.net/images/anime/16/100015.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/16/200015.jpg",
  chapitres: "250+",
  date: "2018-08-01",
  statut: "En cours",
  lien: "/blue-lock",
  type: "Anime",
  genre: ["Sport", "Psychologique", "Drame", "Compétition", "Équipe", "Shonen", "Ambition"]
},
{
  id: 16,
  titre: "Haikyuu!!",
  auteur: "Haruichi Furudate",
  description: "Hinata, petit mais déterminé, vise le sommet du volleyball.",
  description_longue: "Shoyo Hinata rejoint le club de volleyball de Karasuno malgré sa petite taille. Avec son rival devenu coéquipier Kageyama, il prouve que la passion surpasse les limites physiques.",
  image: "https://cdn.myanimelist.net/images/anime/17/100016.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/17/200016.jpg",
  chapitres: "402",
  date: "2012-02-20",
  statut: "Terminé",
  lien: "/haikyuu",
  type: "Anime",
  genre: ["Sport", "Amitié", "Drame", "Comédie", "École", "Motivation", "Shonen"]
},
{
  id: 17,
  titre: "Solo Leveling",
  auteur: "Chugong",
  description: "Un chasseur faible devient incroyablement puissant grâce à un système mystérieux.",
  description_longue: "Sung Jin-Woo découvre un système qui lui permet de 'level up'. Sa montée en puissance bouleverse l'équilibre entre chasseurs et monstres dans un monde où les portails menacent l'humanité.",
  image: "https://cdn.myanimelist.net/images/anime/18/100017.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/18/200017.jpg",
  chapitres: "179",
  date: "2016-03-04",
  statut: "Terminé",
  lien: "/solo-leveling",
  type: "Manhwa",
  genre: ["Action", "Fantasy", "Aventure", "Surnaturel", "Jeu vidéo", "Dark Fantasy", "Puissance"]
},
{
  id: 18,
  titre: "Vinland Saga",
  auteur: "Makoto Yukimura",
  description: "Thorfinn cherche vengeance dans l'ère viking avant de trouver la paix.",
  description_longue: "Thorfinn, guerrier viking, poursuit Askeladd pour venger son père. Son voyage de haine se transforme en quête de rédemption vers un lieu mythique : le Vinland.",
  image: "https://cdn.myanimelist.net/images/anime/19/100018.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/19/200018.jpg",
  chapitres: "210+",
  date: "2005-04-13",
  statut: "En cours",
  lien: "/vinland-saga",
  type: "Anime",
  genre: ["Historique", "Drame", "Action", "Aventure", "Guerre", "Vikings", "Tragédie"]
},
{
  id: 19,
  titre: "Spy x Family",
  auteur: "Tatsuya Endo",
  description: "Un espion, une tueuse et une télépathe forment une fausse famille.",
  description_longue: "Pour sa mission, l'espion Twilight crée une famille de façade avec Yor, tueuse à gages, et Anya, enfant télépathe. Leurs secrets créent des situations hilarantes et touchantes.",
  image: "https://cdn.myanimelist.net/images/anime/20/100019.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/20/200019.jpg",
  chapitres: "90+",
  date: "2019-03-25",
  statut: "En cours",
  lien: "/spy-x-family",
  type: "Anime",
  genre: ["Comédie", "Action", "Espionnage", "Famille", "Slice of Life", "Surnaturel", "Shonen"]
},
{
  id: 20,
  titre: "The Seven Deadly Sins",
  auteur: "Nakaba Suzuki",
  description: "Sept criminels légendaires se réunissent pour sauver le royaume.",
  description_longue: "Meliodas et les Seven Deadly Sins, autrefois héros puis traîtres, combattent pour libérer le royaume de Liones d'une tyrannie magique. Leurs péchés passés resurgissent à chaque bataille.",
  image: "https://cdn.myanimelist.net/images/anime/21/100020.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/21/200020.jpg",
  chapitres: "346",
  date: "2012-10-10",
  statut: "Terminé",
  lien: "/the-seven-deadly-sins",
  type: "Anime",
  genre: ["Action", "Aventure", "Fantasy", "Magie", "Comédie", "Drame", "Chevalerie"]
},
{
  id: 21,
  titre: "Umineko no Naku Koro ni",
  auteur: "Ryukishi07",
  description: "Une famille se réunit sur une île où un mystère meurtrier les attend.",
  description_longue: "Sur l'île de Rokkenjima, la famille Ushiromiya est confrontée à une série de meurtres rituels. Entre sorcières et énigmes, la vérité se cache derrière plusieurs couches de mensonges.",
  image: "https://cdn.myanimelist.net/images/anime/23/100022.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/23/200022.jpg",
  chapitres: "8 épisodes",
  date: "2007-08-17",
  statut: "Terminé",
  lien: "/umineko-no-naku-koro-ni",
  type: "Visual Novel",
  genre: ["Mystère", "Psychologique", "Horreur", "Surnaturel", "Thriller", "Drame", "Fantasy"]
},
{
  id: 22,
  titre: "Mo Dao Zu Shi",
  auteur: "Mo Xiang Tong Xiu",
  description: "Un cultivateur ressuscite pour démêler les mystères de sa mort.",
  description_longue: "Wei Wuxian revient d'entre les morts 13 ans après sa chute. Aux côtés de Lan Wangji, il explore un monde de cultivation, de secrets ancestraux et d'amour interdit.",
  image: "https://cdn.myanimelist.net/images/anime/24/100023.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/24/200023.jpg",
  chapitres: "113",
  date: "2015-10-31",
  statut: "Terminé",
  lien: "/mo-dao-zu-shi",
  type: "Anime",
  genre: ["Fantasy", "Action", "Drame", "Romance", "Surnaturel", "Historique", "BL"]
},
{
  id: 23,
  titre: "Monogatari Series",
  auteur: "Nisioisin",
  description: "Araragi aide des filles tourmentées par des phénomènes surnaturels.",
  description_longue: "Koyomi Araragi, ancien vampire, rencontre des personnes affectées par des aberrations liées à leurs traumatismes. Dialogues philosophiques et visuels stylisés définissent cette série unique.",
  image: "https://cdn.myanimelist.net/images/anime/25/100024.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/25/200024.jpg",
  chapitres: "30+ volumes",
  date: "2006-11-01",
  statut: "En cours",
  lien: "/monogatari-series",
  type: "Anime",
  genre: ["Psychologique", "Surnaturel", "Romance", "Mystère", "Comédie", "Philosophique", "Drame"]
},
{
  id: 24,
  titre: "Kaguya-sama: Love is War",
  auteur: "Aka Akasaka",
  description: "Deux génies du lycée s'affrontent pour faire avouer l'autre en premier.",
  description_longue: "Kaguya Shinomiya et Miyuki Shirogane, tous deux épris l'un de l'autre, mènent des batailles psychologiques hilarantes pour obtenir une confession d'amour.",
  image: "https://cdn.myanimelist.net/images/anime/26/100025.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/26/200025.jpg",
  chapitres: "281",
  date: "2015-05-19",
  statut: "Terminé",
  lien: "/kaguya-sama-love-is-war",
  type: "Manga",
  genre: ["Romance", "Comédie", "École", "Psychologique", "Slice of Life", "Shonen", "Stratégie"]
},
{
  id: 25,
  titre: "Mikkakan no Koufuku",
  auteur: "Sugaru Miaki",
  description: "Un jeune homme vend sa vie restante pour trois jours de bonheur.",
  description_longue: "Sans espoir ni avenir, Kusunoki vend ses années de vie pour de l'argent. Avec Miyagi comme observatrice, il découvre que ces derniers jours peuvent valoir toute une existence.",
  image: "https://cdn.myanimelist.net/images/anime/27/100026.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/27/200026.jpg",
  chapitres: "3 volumes",
  date: "2013-10-11",
  statut: "Terminé",
  lien: "/mikkakan-no-koufuku",
  type: "Manga",
  genre: ["Drame", "Psychologique", "Romance", "Philosophique", "Tragédie", "Slice of Life"]
},
{
  id: 26,
  titre: "Frieren: Beyond Journey's End",
  auteur: "Kanehito Yamada",
  description: "Une elfe immortelle réfléchit sur le temps et l'humanité après la mort de ses compagnons.",
  description_longue: "Frieren, magicienne elfe, entreprend un nouveau voyage pour comprendre les humains qu'elle a côtoyés. Une méditation poétique sur la mémoire, le deuil et les liens.",
  image: "https://cdn.myanimelist.net/images/anime/28/100027.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/28/200027.jpg",
  chapitres: "130+",
  date: "2020-04-28",
  statut: "En cours",
  lien: "/frieren-beyond-journeys-end",
  type: "Manga",
  genre: ["Fantasy", "Aventure", "Drame", "Philosophique", "Slice of Life", "Émotion", "Shonen"]
},
{
  id: 27,
  titre: "Kaoru Hana wa Rin to Saku",
  auteur: "Mikami",
  description: "Deux lycéens de mondes opposés se découvrent mutuellement.",
  description_longue: "Rintaro, délinquant au grand cœur, et Kaoruko, fille modèle, brisent les préjugés en se rapprochant. Une romance pure sur l'acceptation et la sincérité.",
  image: "https://cdn.myanimelist.net/images/anime/29/100028.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/29/200028.jpg",
  chapitres: "70+",
  date: "2021-05-14",
  statut: "En cours",
  lien: "/kaoru-hana-wa-rin-to-saku",
  type: "Manga",
  genre: ["Romance", "École", "Slice of Life", "Drame", "Comédie", "Shonen", "Amitié"]
},
{
  id: 28,
  titre: "GTO - Great Teacher Onizuka",
  auteur: "Tohru Fujisawa",
  description: "Un ancien voyou devient professeur pour transformer des vies.",
  description_longue: "Eikichi Onizuka, ex-membre de gang, utilise des méthodes peu orthodoxes pour gagner le respect de ses élèves rebelles et leur redonner espoir.",
  image: "https://cdn.myanimelist.net/images/anime/30/100029.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/30/200029.jpg",
  chapitres: "201",
  date: "1997-01-08",
  statut: "Terminé",
  lien: "/gto-great-teacher-onizuka",
  type: "Manga",
  genre: ["Comédie", "Drame", "École", "Slice of Life", "Motivation", "Société", "Shonen"]
},
{
  id: 29,
  titre: "A Silent Voice",
  auteur: "Yoshitoki Oima",
  description: "Un ancien harceleur cherche le pardon de sa victime sourde.",
  description_longue: "Shoya Ishida tente de se racheter auprès de Shoko Nishimiya après l'avoir harcelée enfant. Un récit bouleversant sur le remords, le handicap et la rédemption.",
  image: "https://cdn.myanimelist.net/images/anime/31/100030.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/31/200030.jpg",
  chapitres: "62",
  date: "2013-08-07",
  statut: "Terminé",
  lien: "/a-silent-voice",
  type: "Manga",
  genre: ["Drame", "Romance", "Slice of Life", "Psychologique", "Société", "Émotion", "Shonen"]
},
{
  id: 30,
  titre: "March Comes in Like a Lion",
  auteur: "Chica Umino",
  description: "Un jeune prodige du shogi lutte contre la solitude.",
  description_longue: "Rei Kiriyama, champion de shogi orphelin, trouve chaleur et humanité auprès d'une famille aimante. Un drame contemplatif sur la dépression et la guérison.",
  image: "https://cdn.myanimelist.net/images/anime/32/100031.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/32/200031.jpg",
  chapitres: "190+",
  date: "2007-07-14",
  statut: "En cours",
  lien: "/march-comes-in-like-a-lion",
  type: "Manga",
  genre: ["Drame", "Slice of Life", "Psychologique", "Émotion", "Société", "Motivation", "Shogi"]
},
{
  id: 31,
  titre: "The Apothecary Diaries",
  auteur: "Natsu Hyuuga",
  description: "Une apothicaire résout des mystères dans le palais impérial.",
  description_longue: "Maomao, experte en poisons et médecine, se retrouve servante au palais. Son intelligence aiguë l'entraîne dans des intrigues politiques fascinantes.",
  image: "https://cdn.myanimelist.net/images/anime/33/100032.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/33/200032.jpg",
  chapitres: "60+",
  date: "2017-09-09",
  statut: "En cours",
  lien: "/the-apothecary-diaries",
  type: "Manga",
  genre: ["Mystère", "Historique", "Drame"]
},
{
  id: 32,
  titre: "86 - Eighty Six",
  auteur: "Asato Asato",
  description: "Des soldats discriminés combattent dans une guerre oubliée.",
  description_longue: "La République de San Magnolia prétend être en paix, mais les '86' mènent une guerre sanglante. Shin et ses camarades affrontent l'injustice et la déshumanisation.",
  image: "https://cdn.myanimelist.net/images/anime/34/100033.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/34/200033.jpg",
  chapitres: "12 volumes",
  date: "2017-02-10",
  statut: "En cours",
  lien: "/86-eighty-six",
  type: "Light Novel",
  genre: ["Science-fiction", "Drame", "Militaire"]
},
{
  id: 33,
  titre: "Re:Zero",
  auteur: "Tappei Nagatsuki",
  description: "Subaru revit sans cesse sa mort dans un monde fantastique.",
  description_longue: "Subaru Natsuki acquiert le pouvoir de revenir à un point de sauvegarde après sa mort. Chaque boucle révèle de nouvelles horreurs et l'importance de chaque choix.",
  image: "https://cdn.myanimelist.net/images/anime/38/100037.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/38/200037.jpg",
  chapitres: "35+ volumes",
  date: "2014-01-23",
  statut: "En cours",
  lien: "/rezero-starting-life-in-another-world",
  type: "Light Novel",
  genre: ["Fantasy", "Psychologique", "Drame"]
},
{
  id: 34,
  titre: "Yona of the Dawn",
  auteur: "Mizuho Kusanagi",
  description: "Une princesse renversée rassemble les quatre dragons pour reconquérir son royaume.",
  description_longue: "La princesse Yona fuit après le meurtre de son père. Accompagnée de Son Hak et des guerriers dragons, elle découvre la force et la détermination.",
  image: "https://cdn.myanimelist.net/images/anime/39/100038.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/39/200038.jpg",
  chapitres: "240+",
  date: "2009-08-05",
  statut: "En cours",
  lien: "/yona-of-the-dawn",
  type: "Manga",
  genre: ["Aventure", "Fantasy", "Romance"]
},
{
  id: 35,
  titre: "Heaven Official's Blessing",
  auteur: "Mo Xiang Tong Xiu",
  description: "Un dieu déchu revient pour la troisième fois au paradis céleste.",
  description_longue: "Xie Lian, prince devenu dieu puis banni, monte une troisième fois aux cieux. Avec Hua Cheng à ses côtés, il affronte son passé tragique et des mystères divins.",
  image: "https://cdn.myanimelist.net/images/anime/40/100039.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/40/200039.jpg",
  chapitres: "244",
  date: "2017-06-16",
  statut: "Terminé",
  lien: "/heaven-officials-blessing",
  type: "Light Novel",
  genre: ["Fantasy", "Romance", "Drame"]
},
{
  id: 36,
  titre: "The Climber",
  auteur: "Shinichi Sakamoto",
  description: "Un solitaire trouve sa raison de vivre dans l'escalade extrême.",
  description_longue: "Mori Buntaro, asocial et incompris, découvre l'alpinisme et y trouve sa liberté. Une ascension physique et spirituelle vers les sommets les plus dangereux.",
  image: "https://cdn.myanimelist.net/images/anime/41/100040.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/41/200040.jpg",
  chapitres: "170",
  date: "2007-01-30",
  statut: "Terminé",
  lien: "/the-climber-kokou-no-hito",
  type: "Manga",
  genre: ["Drame", "Psychologique", "Sport"]
},
{
  id: 37,
  titre: "Nausicaä de la Vallée du Vent",
  auteur: "Hayao Miyazaki",
  description: "Une princesse lutte pour l'harmonie entre humains et nature toxique.",
  description_longue: "Nausicaä protège son peuple dans un monde post-apocalyptique envahi par une forêt empoisonnée. Un chef-d'œuvre écologique sur la coexistence et le sacrifice.",
  image: "https://cdn.myanimelist.net/images/anime/46/100045.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/46/200045.jpg",
  chapitres: "59",
  date: "1982-02-24",
  statut: "Terminé",
  lien: "/nausicaa-de-la-vallee-du-vent",
  type: "Manga",
  genre: ["Aventure", "Science-fiction", "Drame"]
},
{
  id: 38,
  titre: "Delicious in Dungeon",
  auteur: "Ryoko Kui",
  description: "Des aventuriers cuisinent des monstres pour survivre dans un donjon.",
  description_longue: "Laios et son équipe explorent un donjon en mangeant les créatures qu'ils combattent. Une aventure culinaire fantastique pleine d'humour et de stratégie.",
  image: "https://cdn.myanimelist.net/images/anime/47/100046.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/47/200046.jpg",
  chapitres: "97",
  date: "2014-02-15",
  statut: "Terminé",
  lien: "/delicious-in-dungeon",
  type: "Manga",
  genre: ["Fantasy", "Aventure", "Comédie"]
},
{
  id: 39,
  titre: "Ascendance of a Bookworm",
  auteur: "Miya Kazuki",
  description: "Une bibliophile réincarnée crée des livres dans un monde médiéval.",
  description_longue: "Urano renaît dans un monde sans livres. Déterminée à lire à nouveau, elle invente papier, encre et imprimerie, bouleversant la société.",
  image: "https://cdn.myanimelist.net/images/anime/48/100047.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/48/200047.jpg",
  chapitres: "33+ volumes",
  date: "2013-09-24",
  statut: "En cours",
  lien: "/ascendance-of-a-bookworm",
  type: "Light Novel",
  genre: ["Fantasy", "Slice of Life", "Drame"]
},
{
  id: 40,
  titre: "Classroom of the Elite",
  auteur: "Shogo Kinugasa",
  description: "Un lycée élitiste cache une compétition impitoyable entre classes.",
  description_longue: "Ayanokoji Kiyotaka rejoint une école prestigieuse où les élèves s'affrontent pour gravir les échelons. Derrière son apparence ordinaire se cache un génie manipulateur.",
  image: "https://cdn.myanimelist.net/images/anime/49/100048.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/49/200048.jpg",
  chapitres: "18+ volumes",
  date: "2015-05-25",
  statut: "En cours",
  lien: "/classroom-of-the-elite",
  type: "Light Novel",
  genre: ["Psychologique", "School Life", "Thriller"]
},
 {
  id: 41,
  titre: "No Home",
  auteur: "Wanan",
  description: "Deux SDF lycéens survivent ensemble dans les rues de Séoul.",
  description_longue: "Haejoon et Eunyung, sans-abri aux personnalités opposées, cohabitent difficilement. Une histoire touchante sur la survie, le trauma et l'amitié improbable.",
  image: "https://cdn.myanimelist.net/images/anime/50/100049.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/50/200049.jpg",
  chapitres: "270+",
  date: "2019-03-30",
  statut: "En cours",
  lien: "/no-home",
  type: "Manhwa",
  genre: ["Drame", "Psychologique", "Slice of Life"]
},
{
  id: 42,
  titre: "I Sold My Life for Ten Thousand Yen per Year",
  auteur: "Sugaru Miaki",
  description: "Un jeune homme vend sa vie restante pour sortir de la misère.",
  description_longue: "Kusunoki, désespéré, vend 30 ans de sa vie pour 300 000 yens. Avec Miyagi comme observatrice, il découvre la valeur des moments qu'il lui reste.",
  image: "https://cdn.myanimelist.net/images/anime/51/100050.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/51/200050.jpg",
  chapitres: "3 volumes",
  date: "2016-08-25",
  statut: "Terminé",
  lien: "/i-sold-my-life-for-ten-thousand-yen-per-year",
  type: "Light Novel",
  genre: ["Drame", "Romance", "Psychologique"]
},
{
  id: 43,
  titre: "Fight Class 3",
  auteur: "PaekHyuk",
  description: "Un lycéen rejoint un tournoi de combat underground pour venger son père.",
  description_longue: "Nam-soon intègre une classe spéciale où les élèves s'affrontent violemment. Action brutale et quête de justice dans un manhwa sans compromis.",
  image: "https://cdn.myanimelist.net/images/anime/52/100051.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/52/200051.jpg",
  chapitres: "120+",
  date: "2019-08-19",
  statut: "En cours",
  lien: "/fight-class-3",
  type: "Manhwa",
  genre: ["Action", "Drame", "Arts Martiaux"]
},
{
  id: 44,
  titre: "Oregairu",
  auteur: "Wataru Watari",
  description: "Un lycéen cynique aide les autres malgré sa vision pessimiste.",
  description_longue: "Hachiman Hikigaya rejoint le club de service pour changer sa personnalité. Entre romance et philosophie, il apprend que les relations authentiques ont un prix.",
  image: "https://cdn.myanimelist.net/images/anime/54/100053.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/54/200053.jpg",
  chapitres: "14 volumes",
  date: "2011-03-18",
  statut: "Terminé",
  lien: "/oregairu",
  type: "Light Novel",
  genre: ["Romance", "School Life", "Psychologique"]
},
{
  id: 45,
  titre: "Space Brothers",
  auteur: "Chuya Koyama",
  description: "Deux frères poursuivent leur rêve d'enfance de devenir astronautes.",
  description_longue: "Mutta Nanba, au chômage, décide de rattraper son frère cadet devenu astronaute. Un récit inspirant sur la persévérance et la passion pour l'espace.",
  image: "https://cdn.myanimelist.net/images/anime/56/100055.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/56/200055.jpg",
  chapitres: "420+",
  date: "2008-01-01",
  statut: "En cours",
  lien: "/space-brothers",
  type: "Manga",
  genre: ["Drame", "Science-fiction", "Slice of Life"]
},
{
  id: 46,
  titre: "Hajime no Ippo",
  auteur: "George Morikawa",
  description: "Un lycéen timide découvre la boxe et gravit les rangs.",
  description_longue: "Ippo Makunouchi, souvent harcelé, trouve sa force dans la boxe. Son ascension vers le titre mondial est jalonnée de combats épiques et de détermination.",
  image: "https://cdn.myanimelist.net/images/anime/57/100056.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/57/200056.jpg",
  chapitres: "1400+",
  date: "1989-10-11",
  statut: "En cours",
  lien: "/hajime-no-ippo",
  type: "Manga",
  genre: ["Sport", "Action", "Comédie"]
},
{
  id: 47,
  titre: "Kono Oto Tomare!",
  auteur: "Amyu",
  description: "Un club de koto en difficulté renaît grâce à de nouveaux membres passionnés.",
  description_longue: "Chika Kudo, délinquant au passé trouble, rejoint le club de koto. Ensemble, les membres créent une harmonie musicale et personnelle magnifique.",
  image: "https://cdn.myanimelist.net/images/anime/58/100057.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/58/200057.jpg",
  chapitres: "34 volumes",
  date: "2012-08-30",
  statut: "Terminé",
  lien: "/kono-oto-tomare",
  type: "Manga",
  genre: ["Musique", "Romance", "School Life"]
},
{
  id: 48,
  titre: "Shoujo Shuumatsu Ryokou",
  auteur: "Tsukumizu",
  description: "Deux filles explorent un monde post-apocalyptique à bord d'un véhicule.",
  description_longue: "Chito et Yuuri voyagent dans une civilisation morte, cherchant nourriture et sens. Une méditation douce-amère sur la solitude et l'espoir.",
  image: "https://cdn.myanimelist.net/images/anime/59/100058.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/59/200058.jpg",
  chapitres: "47",
  date: "2014-02-21",
  statut: "Terminé",
  lien: "/shoujo-shuumatsu-ryokou",
  type: "Manga",
  genre: ["Aventure", "Slice of Life", "Science-fiction"]
},
{
  id: 49,
  titre: "Made in Abyss",
  auteur: "Akihito Tsukushi",
  description: "Une jeune fille descend dans un gouffre mystérieux pour retrouver sa mère.",
  description_longue: "Riko et Reg explorent l'Abysse, lieu magnifique mais mortel. Chaque couche révèle des merveilles et des horreurs dans cette aventure sombre et captivante.",
  image: "https://cdn.myanimelist.net/images/anime/60/100059.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/60/200059.jpg",
  chapitres: "60+",
  date: "2012-10-20",
  statut: "En cours",
  lien: "/made-in-abyss",
  type: "Manga",
  genre: ["Aventure", "Fantasy", "Drame"]
},
{
  id: 50,
  titre: "One Punch Man",
  auteur: "ONE",
  description: "Un héros peut vaincre n'importe quel ennemi d'un seul coup de poing.",
  description_longue: "Saitama, devenu trop puissant, s'ennuie dans un monde de héros et de monstres. Une parodie hilarante des shonen avec des combats spectaculaires.",
  image: "https://cdn.myanimelist.net/images/anime/62/100061.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/62/200061.jpg",
  chapitres: "190+",
  date: "2009-06-03",
  statut: "En cours",
  lien: "/one-punch-man",
  type: "Manga",
  genre: ["Action", "Comédie", "Super-héros"]
},
  {
  id: 51,
  titre: "Mushishi",
  auteur: "Yuki Urushibara",
  description: "Un voyageur étudie des créatures primitives appelées Mushi.",
  description_longue: "Ginko parcourt le Japon pour comprendre les Mushi, formes de vie entre esprit et matière. Une série contemplative sur la nature et l'existence.",
  image: "https://cdn.myanimelist.net/images/anime/64/100063.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/64/200063.jpg",
  chapitres: "50",
  date: "1999-10-28",
  statut: "Terminé",
  lien: "/mushishi",
  type: "Manga",
  genre: ["Fantastique", "Mystère", "Slice of Life"]
},
{
  id: 52,
  titre: "Medalist",
  auteur: "Tsurumaikada",
  description: "Une patineuse artistique et son entraîneur visent les médailles olympiques.",
  description_longue: "Inori Yuitsuka rêve de devenir championne de patinage malgré son âge tardif. Avec Tsukasa Akeuraji, elle défie les limites du sport et de la passion.",
  image: "https://cdn.myanimelist.net/images/anime/65/100064.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/65/200064.jpg",
  chapitres: "50+",
  date: "2020-03-13",
  statut: "En cours",
  lien: "/medalist",
  type: "Manga",
  genre: ["Sport", "Drame", "Slice of Life"]
},
{
  id: 53,
  titre: "Beck",
  auteur: "Harold Sakuishi",
  description: "Un lycéen ordinaire rejoint un groupe de rock et découvre la musique.",
  description_longue: "Koyuki rencontre Ryusuke et entre dans le monde du rock. Beck suit leur ascension tumultueuse vers la gloire musicale.",
  image: "https://cdn.myanimelist.net/images/anime/66/100065.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/66/200065.jpg",
  chapitres: "103",
  date: "1999-09-17",
  statut: "Terminé",
  lien: "/beck",
  type: "Manga",
  genre: ["Musique", "Slice of Life", "Drame"]
},
{
  id: 54,
  titre: "The Horizon",
  auteur: "Jeong Ji-Hoon",
  description: "Un garçon affronte des créatures pour protéger l'humanité au bord du gouffre.",
  description_longue: "Dans un monde envahi par des monstres, les survivants luttent depuis une dernière forteresse. Action intense et survie désespérée définissent ce manhwa.",
  image: "https://cdn.myanimelist.net/images/anime/67/100066.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/67/200066.jpg",
  chapitres: "120+",
  date: "2020-09-14",
  statut: "En cours",
  lien: "/the-horizon",
  type: "Manhwa",
  genre: ["Action", "Drame", "Post-apocalyptique"]
},
{
  id: 55,
  titre: "Dorohedoro",
  auteur: "Q Hayashida",
  description: "Un homme à tête de reptile cherche le sorcier qui l'a maudit.",
  description_longue: "Caiman, amnésique et défiguré, traque les sorciers dans un monde dystopique. Un univers bizarre, violent et fascinant où magie et gore cohabitent.",
  image: "https://cdn.myanimelist.net/images/anime/69/100068.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/69/200068.jpg",
  chapitres: "167",
  date: "2000-11-30",
  statut: "Terminé",
  lien: "/dorohedoro",
  type: "Manga",
  genre: ["Action", "Fantastique", "Horreur"]
},
{
  id: 56,
  titre: "Witch Hat Atelier",
  auteur: "Kamome Shirahama",
  description: "Une jeune fille découvre le secret de la magie et devient apprentie sorcière.",
  description_longue: "Coco, fascinée par la magie, apprend qu'elle est accessible à tous. Sous la tutelle de Qifrey, elle explore un monde enchanteur rempli de mystères.",
  image: "https://cdn.myanimelist.net/images/anime/72/100071.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/72/200071.jpg",
  chapitres: "70+",
  date: "2016-07-22",
  statut: "En cours",
  lien: "/witch-hat-atelier",
  type: "Manga",
  genre: ["Fantasy", "Aventure", "Drame"]
},
{
  id: 57,
  titre: "Natsume's Book of Friends",
  auteur: "Yuki Midorikawa",
  description: "Un lycéen rend leurs noms aux yokai liés par sa grand-mère.",
  description_longue: "Natsume Takashi hérite d'un livre contenant les noms de yokai. Avec Nyanko-sensei, il libère les esprits dans des histoires douces et mélancoliques.",
  image: "https://cdn.myanimelist.net/images/anime/73/100072.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/73/200072.jpg",
  chapitres: "120+",
  date: "2005-07-05",
  statut: "En cours",
  lien: "/natsumes-book-of-friends",
  type: "Manga",
  genre: ["Fantastique", "Slice of Life", "Drame"]
},
{
  id: 58,
  titre: "Ao Ashi",
  auteur: "Yugo Kobayashi",
  description: "Un jeune footballeur rejoint une académie d'élite pour réaliser son rêve.",
  description_longue: "Ashito Aoi, talent brut du football, apprend la tactique et le travail d'équipe. Un manga sportif réaliste sur l'ambition et le sacrifice.",
  image: "https://cdn.myanimelist.net/images/anime/74/100073.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/74/200073.jpg",
  chapitres: "340+",
  date: "2015-01-23",
  statut: "En cours",
  lien: "/ao-ashi",
  type: "Manga",
  genre: ["Sport", "Drame", "School Life"]
},
{
  id: 59,
  titre: "Bloom Into You",
  auteur: "Nio Nakatani",
  description: "Deux lycéennes explorent un amour complexe et fragile.",
  description_longue: "Yuu Koito ne comprend pas l'amour jusqu'à sa rencontre avec Touko Nanami. Une romance yuri subtile sur l'identité et l'acceptation de soi.",
  image: "https://cdn.myanimelist.net/images/anime/77/100076.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/77/200076.jpg",
  chapitres: "50",
  date: "2015-04-27",
  statut: "Terminé",
  lien: "/bloom-into-you",
  type: "Manga",
  genre: ["Romance", "Yuri", "School Life"]
},
{
  id: 60,
  titre: "Akira",
  auteur: "Katsuhiro Otomo",
  description: "Dans un Tokyo post-apocalyptique, des adolescents possèdent des pouvoirs psychiques.",
  description_longue: "Kaneda et Tetsuo sont pris dans un complot gouvernemental impliquant Akira, pouvoir ultime. Un chef-d'œuvre cyberpunk sur le pouvoir et la destruction.",
  image: "https://cdn.myanimelist.net/images/anime/78/100077.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/78/200077.jpg",
  chapitres: "120",
  date: "1982-12-20",
  statut: "Terminé",
  lien: "/akira",
  type: "Manga",
  genre: ["Science-fiction", "Action", "Cyberpunk"]
},
 {
    id: 61,
    titre: "Violet Evergarden",
    auteur: "Kana Akatsuki",
    description: "Une ancienne soldate devient écrivaine publique pour comprendre les émotions.",
    description_longue: "Violet Evergarden, arme humaine, apprend la signification de 'je t'aime' en écrivant des lettres pour les autres. Un récit poignant sur l'humanité retrouvée.",
    image: "https://cdn.myanimelist.net/images/anime/79/100078.jpg",
    iconImage: "https://cdn.myanimelist.net/images/characters/79/200078.jpg",
    chapitres: "4 volumes",
    date: "2015-12-25",
    statut: "Terminé",
    lien: "/violet-evergarden",
    type: "Light Novel",
    genre: ["Drame", "Romance", "Psychologique"]
  },
  {
    id: 62,
    titre: "Golden Kamuy",
    auteur: "Satoru Noda",
    description: "Un vétéran et une jeune Ainu cherchent un trésor caché en Hokkaido.",
    description_longue: "Sugimoto 'l'Immortel' traque un or légendaire tatoué sur des prisonniers. Aventure historique mêlant culture ainu, humour et action brutale.",
    image: "https://cdn.myanimelist.net/images/anime/82/100081.jpg",
    iconImage: "https://cdn.myanimelist.net/images/characters/82/200081.jpg",
    chapitres: "314",
    date: "2014-08-21",
    statut: "Terminé",
    lien: "/golden-kamuy",
    type: "Manga",
    genre: ["Aventure", "Historique", "Action", "Comédie"]
  },
  {
    id: 63,
    titre: "Omniscient Reader's Viewpoint",
    auteur: "Sing Shong",
    description: "Un lecteur se retrouve piégé dans son webnovel préféré devenu réalité.",
    description_longue: "Kim Dokja, seul lecteur d'un roman web, utilise sa connaissance de l'histoire pour survivre dans un monde apocalyptique. Méta-fiction brillante et addictive.",
    image: "https://cdn.myanimelist.net/images/anime/83/100082.jpg",
    iconImage: "https://cdn.myanimelist.net/images/characters/83/200082.jpg",
    chapitres: "180+",
    date: "2020-06-01",
    statut: "En cours",
    lien: "/omniscient-readers-viewpoint",
    type: "Manhwa",
    genre: ["Action", "Fantastique", "Psychologique", "Thriller"]
  },
  {
    id: 64,
    titre: "Gintama",
    auteur: "Hideaki Sorachi",
    description: "Dans un Japon futuriste envahi par des aliens, un samouraï fait des petits boulots.",
    description_longue: "Gintoki Sakata et ses compagnons vivent des aventures absurdes et touchantes. Comédie parodique avec des arcs dramatiques puissants.",
    image: "https://cdn.myanimelist.net/images/anime/86/100085.jpg",
    iconImage: "https://cdn.myanimelist.net/images/characters/86/200085.jpg",
    chapitres: "704",
    date: "2003-12-08",
    statut: "Terminé",
    lien: "/gintama",
    type: "Manga",
    genre: ["Comédie", "Action", "Science-fiction", "Drame"]
  },
  {
    id: 65,
    titre: "Sayonara Eri",
    auteur: "Tatsuki Fujimoto",
    description: "Un adolescent filme la vie de sa mère mourante puis rencontre une fille mystérieuse.",
    description_longue: "Yuta crée des films pour échapper à sa réalité tragique. Sayonara Eri, récit court mais intense, brouille les lignes entre vérité et fiction.",
    image: "https://cdn.myanimelist.net/images/anime/88/100087.jpg",
    iconImage: "https://cdn.myanimelist.net/images/characters/88/200087.jpg",
    chapitres: "1 (one-shot)",
    date: "2022-04-11",
    statut: "Terminé",
    lien: "/sayonara-eri",
    type: "Manga",
    genre: ["Drame", "Psychologique", "Tranche de vie"]
  },
  {
    id: 66,
    titre: "ReLIFE",
    auteur: "Yayoi So",
    description: "Un chômeur de 27 ans rajeunit pour revivre sa dernière année de lycée.",
    description_longue: "Arata Kaizaki participe à une expérience lui permettant de corriger ses erreurs passées. Une réflexion touchante sur la seconde chance et la maturité.",
    image: "https://cdn.myanimelist.net/images/anime/91/100090.jpg",
    iconImage: "https://cdn.myanimelist.net/images/characters/91/200090.jpg",
    chapitres: "222",
    date: "2013-10-12",
    statut: "Terminé",
    lien: "/relife",
    type: "Manhwa",
    genre: ["Romance", "Drame", "Tranche de vie"]
  },
  {
    id: 67,
    titre: "Pluto",
    auteur: "Naoki Urasawa",
    description: "Un robot enquête sur des meurtres de robots et d'humains influents.",
    description_longue: "Gesicht, détective robot, découvre un complot lié à la guerre. Réinterprétation sombre et philosophique d'Astro Boy sur la conscience et la guerre.",
    image: "https://cdn.myanimelist.net/images/anime/96/100095.jpg",
    iconImage: "https://cdn.myanimelist.net/images/characters/96/200095.jpg",
    chapitres: "65",
    date: "2003-09-05",
    statut: "Terminé",
    lien: "/pluto",
    type: "Manga",
    genre: ["Science-fiction", "Mystère", "Drame", "Psychologique"]
  },
  {
    id: 68,
    titre: "Mob Psycho 100",
    auteur: "ONE",
    description: "Un collégien aux pouvoirs psychiques tente de vivre normalement.",
    description_longue: "Shigeo Kageyama, dit Mob, contrôle ses émotions pour ne pas exploser. Entre croissance personnelle et combats spectaculaires, une série profondément humaine.",
    image: "https://cdn.myanimelist.net/images/anime/98/100097.jpg",
    iconImage: "https://cdn.myanimelist.net/images/characters/98/200097.jpg",
    chapitres: "101",
    date: "2012-04-18",
    statut: "Terminé",
    lien: "/mob-psycho-100",
    type: "Manga",
    genre: ["Action", "Surnaturel", "Comédie", "Drame"]
  },
  {
    id: 69,
    titre: "Blue Period",
    auteur: "Tsubasa Yamaguchi",
    description: "Un lycéen découvre sa passion pour l'art et vise l'université des Beaux-Arts.",
    description_longue: "Yatora Yaguchi, étudiant modèle ennuyé, trouve un sens à sa vie dans la peinture. Un récit authentique sur la création artistique et le doute.",
    image: "https://cdn.myanimelist.net/images/anime/100/100099.jpg",
    iconImage: "https://cdn.myanimelist.net/images/characters/100/200099.jpg",
    chapitres: "60+",
    date: "2017-06-26",
    statut: "En cours",
    lien: "/blue-period",
    type: "Manga",
    genre: ["Drame", "Tranche de vie", "Psychologique", "Artistique"]
  },
  {
    id: 70,
    titre: "Overlord",
    auteur: "Kugane Maruyama",
    description: "Un joueur reste coincé dans un MMORPG en tant que seigneur squelette tout-puissant.",
    description_longue: "Momonga dirige sa guilde devenue réelle dans un nouveau monde. Entre stratégie et domination, il cherche d'autres joueurs tout en bâtissant un empire.",
    image: "https://cdn.myanimelist.net/images/anime/1/100100.jpg",
    iconImage: "https://cdn.myanimelist.net/images/characters/101/200100.jpg",
    chapitres: "16+ volumes",
    date: "2010-07-30",
    statut: "En cours",
    lien: "/overlord",
    type: "Light Novel",
    genre: ["Fantasy", "Action", "Isekai", "Drame"]
  },
 {
    id: 71,
    titre: "Seasons of Blossom",
    auteur: "Hongduck",
    description: "Quatre histoires entrelacées explorent l'amour, le deuil et la guérison au lycée.",
    description_longue: "À travers les saisons, différents couples affrontent leurs traumatismes et apprennent à s'ouvrir. Un manhwa émotionnel sur la cicatrisation des blessures invisibles.",
    image: "https://cdn.myanimelist.net/images/anime/2/100101.jpg",
    iconImage: "https://cdn.myanimelist.net/images/characters/102/200101.jpg",
    chapitres: "130+",
    date: "2019-03-01",
    statut: "En cours",
    lien: "/seasons-of-blossom",
    type: "Manhwa",
    genre: ["Romance", "Drame", "Tranche de vie", "Psychologique"]
  },
  {
    id: 72,
    titre: "Skip and Loafer",
    auteur: "Misaki Takamatsu",
    description: "Une fille de campagne s'adapte à la vie lycéenne à Tokyo.",
    description_longue: "Mitsumi Iwakura, déterminée et naïve, navigue dans son nouveau lycée avec optimisme. Une comédie slice-of-life rafraîchissante sur l'amitié et la croissance.",
    image: "https://cdn.myanimelist.net/images/anime/3/100102.jpg",
    iconImage: "https://cdn.myanimelist.net/images/characters/103/200102.jpg",
    chapitres: "60+",
    date: "2018-08-08",
    statut: "En cours",
    lien: "/skip-and-loafer",
    type: "Manga",
    genre: ["Comédie", "Tranche de vie", "Romance", "Scolaire"]
  },
  {
    id: 73,
    titre: "Wind Breaker",
    auteur: "Satoru Nii",
    description: "Un délinquant rejoint une école où les voyous protègent la ville.",
    description_longue: "Haruka Sakura arrive à Furin High, où les combattants défendent leur quartier. Action intense et camaraderie dans un shonen revigorant.",
    image: "https://cdn.myanimelist.net/images/anime/4/100103.jpg",
    iconImage: "https://cdn.myanimelist.net/images/characters/104/200103.jpg",
    chapitres: "140+",
    date: "2021-01-13",
    statut: "En cours",
    lien: "/wind-breaker",
    type: "Manga",
    genre: ["Action", "Combat", "Amitié", "Scolaire"]
  },
  {
    id: 74,
    titre: "Hyouka",
    auteur: "Honobu Yonezawa",
    description: "Un lycéen économe en énergie résout des mystères du quotidien.",
    description_longue: "Houtarou Oreki rejoint le club de littérature classique où il déchiffre des énigmes mineures mais fascinantes. Mystère intimiste et magnifiquement écrit.",
    image: "https://cdn.myanimelist.net/images/anime/5/100104.jpg",
    iconImage: "https://cdn.myanimelist.net/images/characters/105/200104.jpg",
    chapitres: "6 volumes",
    date: "2001-10-31",
    statut: "En cours",
    lien: "/hyouka",
    type: "Light Novel",
    genre: ["Mystère", "Tranche de vie", "Scolaire"]
  },
  {
    id: 75,
    titre: "Your Lie in April",
    auteur: "Naoshi Arakawa",
    description: "Un pianiste prodige retrouve sa passion grâce à une violoniste imprévisible.",
    description_longue: "Kousei Arima, bloqué depuis la mort de sa mère, rencontre Kaori Miyazono qui le ramène à la musique. Romance déchirante sur l'art et le deuil.",
    image: "https://cdn.myanimelist.net/images/anime/6/100105.jpg",
    iconImage: "https://cdn.myanimelist.net/images/characters/106/200105.jpg",
    chapitres: "44",
    date: "2011-04-06",
    statut: "Terminé",
    lien: "/your-lie-in-april",
    type: "Manga",
    genre: ["Drame", "Romance", "Musique", "Tranche de vie"]
  },
  {
    id: 76,
    titre: "KonoSuba",
    auteur: "Natsume Akatsuki",
    description: "Un NEET meurt et renaît dans un monde fantastique avec une déesse inutile.",
    description_longue: "Kazuma Sato forme un groupe dysfonctionnel avec Aqua, Megumin et Darkness. Parodie hilarante des isekai remplie de situations absurdes.",
    image: "https://cdn.myanimelist.net/images/anime/7/100106.jpg",
    iconImage: "https://cdn.myanimelist.net/images/characters/107/200106.jpg",
    chapitres: "17 volumes",
    date: "2013-10-01",
    statut: "Terminé",
    lien: "/konosuba",
    type: "Light Novel",
    genre: ["Comédie", "Fantasy", "Isekai", "Aventure"]
  },
  {
    id: 77,
    titre: "Will You Marry Me Again If You Are Reborn?",
    auteur: "Eno Sumi",
    description: "Un couple de personnes âgées se demande s'ils se retrouveraient dans une autre vie.",
    description_longue: "À travers leurs souvenirs, Toranosuke et Kaoru revivent leur vie ensemble. Un récit tendre sur l'amour qui traverse le temps et les réincarnations.",
    image: "https://cdn.myanimelist.net/images/anime/8/100107.jpg",
    iconImage: "https://cdn.myanimelist.net/images/characters/108/200107.jpg",
    chapitres: "40+",
    date: "2019-11-22",
    statut: "En cours",
    lien: "/will-you-marry-me-again-if-you-are-reborn",
    type: "Manga",
    genre: ["Romance", "Drame", "Tranche de vie", "Surnaturel"]
  },
  {
    id: 78,
    titre: "Kaiji",
    auteur: "Nobuyuki Fukumoto",
    description: "Un homme endetté joue sa vie dans des jeux d'argent mortels.",
    description_longue: "Kaiji Ito affronte des paris psychologiques extrêmes pour survivre. Tension insoutenable et stratégies brillantes dans ce thriller psychologique.",
    image: "https://cdn.myanimelist.net/images/anime/9/100108.jpg",
    iconImage: "https://cdn.myanimelist.net/images/characters/109/200108.jpg",
    chapitres: "400+",
    date: "1996-02-19",
    statut: "En cours",
    lien: "/kaiji",
    type: "Manga",
    genre: ["Psychologique", "Thriller", "Drame"]
  },
  {
    id: 79,
    titre: "Banana Fish",
    auteur: "Akimi Yoshida",
    description: "Un chef de gang new-yorkais enquête sur une drogue mystérieuse.",
    description_longue: "Ash Lynx découvre un complot impliquant 'Banana Fish' qui a détruit son frère. Avec Eiji Okumura, il affronte la mafia dans un thriller noir intense.",
    image: "https://cdn.myanimelist.net/images/anime/10/100109.jpg",
    iconImage: "https://cdn.myanimelist.net/images/characters/110/200109.jpg",
    chapitres: "110",
    date: "1985-05-13",
    statut: "Terminé",
    lien: "/banana-fish",
    type: "Manga",
    genre: ["Action", "Drame", "Thriller", "Crime"]
  },
  {
    id: 80,
    titre: "19 Days",
    auteur: "Old Xian",
    description: "Deux lycéens chinois vivent leur quotidien entre amitié et sentiments troubles.",
    description_longue: "Jian Yi et Zhan Zheng Xi partagent des moments drôles et tendres. Webcomic BL chinois touchant sur les premières émotions et la complicité.",
    image: "https://cdn.myanimelist.net/images/anime/11/100110.jpg",
    iconImage: "https://cdn.myanimelist.net/images/characters/111/200110.jpg",
    chapitres: "400+",
    date: "2013-11-24",
    statut: "En cours",
    lien: "/19-days",
    type: "Manhua",
    genre: ["Comédie", "Tranche de vie", "BL", "Romance"]
  },
{
  id: 81,
  titre: "Chihayafuru",
  auteur: "Yuki Suetsugu",
  description: "Une lycéenne passionnée vise à devenir la meilleure joueuse de karuta.",
  description_longue: "Chihaya Ayase poursuit son rêve de karuta compétitif tout en naviguant entre amour et amitié. Josei captivant mêlant sport, stratégie et émotions.",
  image: "https://cdn.myanimelist.net/images/anime/12/100111.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/112/200111.jpg",
  chapitres: "250+",
  date: "2007-12-28",
  statut: "En cours",
  lien: "/chihayafuru",
  type: "Manga",
  genre: ["Romance", "Sport", "Drame", "Slice of Life"]
},
{
  id: 82,
  titre: "Neon Genesis Evangelion",
  auteur: "Yoshiyuki Sadamoto",
  description: "Des adolescents pilotent des mechas géants contre des anges mystérieux.",
  description_longue: "Shinji Ikari rejoint NERV pour combattre des entités menaçant l'humanité. Déconstruction psychologique du genre mecha explorant trauma et existentialisme.",
  image: "https://cdn.myanimelist.net/images/anime/13/100112.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/113/200112.jpg",
  chapitres: "97",
  date: "1994-12-26",
  statut: "Terminé",
  lien: "/neon-genesis-evangelion",
  type: "Manga",
  genre: ["Psychologique", "Science-Fiction", "Drame", "Action", "Mecha"]
},
{
  id: 83,
  titre: "JoJo's Bizarre Adventure: Diamond is Unbreakable",
  auteur: "Hirohiko Araki",
  description: "Josuke Higashikata protège sa ville de criminels aux pouvoirs Stand.",
  description_longue: "Dans Morioh, Josuke et ses amis affrontent des utilisateurs de Stand dangereux. Quatrième partie culte de JoJo, mêlant mystère, action et style unique.",
  image: "https://cdn.myanimelist.net/images/anime/14/100113.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/114/200113.jpg",
  chapitres: "174",
  date: "1992-05-04",
  statut: "Terminé",
  lien: "/jojos-bizarre-adventure-diamond-is-unbreakable",
  type: "Manga",
  genre: ["Action", "Aventure", "Surnaturel", "Mystère"]
},
{
  id: 84,
  titre: "The Legend of the Northern Blade",
  auteur: "Hae-min",
  description: "Le fils d'un traître restaure l'honneur de son clan dans le monde martial.",
  description_longue: "Jin Mu-Won maîtrise les techniques perdues de son clan pour affronter ceux qui ont détruit sa famille. Manhwa martial arts épique avec des combats spectaculaires.",
  image: "https://cdn.myanimelist.net/images/anime/15/100114.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/115/200114.jpg",
  chapitres: "170+",
  date: "2019-01-22",
  statut: "En cours",
  lien: "/the-legend-of-the-northern-blade",
  type: "Manhwa",
  genre: ["Action", "Arts Martiaux", "Fantasy", "Drame"]
},
{
  id: 85,
  titre: "Webtoon Character Na Kang Lim",
  auteur: "GGULCHAN",
  description: "Un personnage de webtoon prend conscience de son existence fictive.",
  description_longue: "Na Kang Lim découvre qu'il est dans un webtoon et tente de changer son destin. Méta-fiction créative sur l'existence et le libre arbitre.",
  image: "https://cdn.myanimelist.net/images/anime/16/100115.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/116/200115.jpg",
  chapitres: "110+",
  date: "2020-08-17",
  statut: "En cours",
  lien: "/webtoon-character-na-kang-lim",
  type: "Manhwa",
  genre: ["Psychologique", "Fantastique", "Drame", "Méta"]
},
{
  id: 86,
  titre: "The Fable",
  auteur: "Katsuhisa Minami",
  description: "Un tueur légendaire doit vivre une année en civil sans tuer personne.",
  description_longue: "Akira Sato, assassin invincible, se cache dans une vie normale. Comédie noire brillante mêlant action, humour et critique sociale.",
  image: "https://cdn.myanimelist.net/images/anime/17/100116.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/117/200116.jpg",
  chapitres: "240",
  date: "2014-11-15",
  statut: "Terminé",
  lien: "/the-fable",
  type: "Manga",
  genre: ["Action", "Comédie", "Thriller", "Seinen"]
},
{
  id: 87,
  titre: "Pandora Hearts",
  auteur: "Jun Mochizuki",
  description: "Un noble jeté en prison découvre un monde sombre de contrats et de mystères.",
  description_longue: "Oz Vessalius forme un pacte avec Alice, une chaîne, pour échapper à l'Abysse. Fantasy gothique complexe inspirée d'Alice au Pays des Merveilles.",
  image: "https://cdn.myanimelist.net/images/anime/18/100117.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/118/200117.jpg",
  chapitres: "104",
  date: "2006-06-18",
  statut: "Terminé",
  lien: "/pandora-hearts",
  type: "Manga",
  genre: ["Fantasy", "Mystère", "Drame", "Surnaturel"]
},
{
  id: 88,
  titre: "Kino's Journey",
  auteur: "Keiichi Sigsawa",
  description: "Une voyageuse et sa moto parlante explorent des pays aux règles étranges.",
  description_longue: "Kino visite différentes civilisations pendant trois jours, observant sans juger. Récits philosophiques sur la nature humaine et la société.",
  image: "https://cdn.myanimelist.net/images/anime/19/100118.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/119/200118.jpg",
  chapitres: "22+ volumes",
  date: "2000-03-17",
  statut: "En cours",
  lien: "/kino-no-tabi-the-beautiful-world",
  type: "Light Novel",
  genre: ["Philosophique", "Aventure", "Drame"]
},
{
  id: 89,
  titre: "A Bride's Story",
  auteur: "Kaoru Mori",
  description: "Sur la Route de la Soie au 19e siècle, une jeune mariée s'adapte à sa nouvelle famille.",
  description_longue: "Amir épouse Karluk dans l'Asie centrale. Seinen magnifiquement dessiné explorant culture, traditions et humanité avec une richesse historique impressionnante.",
  image: "https://cdn.myanimelist.net/images/anime/20/100119.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/120/200119.jpg",
  chapitres: "100+",
  date: "2008-10-15",
  statut: "En cours",
  lien: "/otoyomegatari",
  type: "Manga",
  genre: ["Historique", "Drame", "Romance", "Slice of Life"]
},
{
  id: 90,
  titre: "Billy Bat",
  auteur: "Naoki Urasawa",
  description: "Un dessinateur découvre que sa création cache une vérité mondiale.",
  description_longue: "Kevin Yamagata suit les traces d'une chauve-souris mystique à travers l'histoire. Thriller conspirationniste ambitieux signé Urasawa et Nagasaki.",
  image: "https://cdn.myanimelist.net/images/anime/21/100120.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/121/200120.jpg",
  chapitres: "165",
  date: "2008-10-16",
  statut: "Terminé",
  lien: "/billy-bat",
  type: "Manga",
  genre: ["Mystère", "Thriller", "Psychologique", "Historique"]
},
 {
  id: 91,
  titre: "Monster",
  auteur: "Naoki Urasawa",
  description: "Un neurochirurgien traque un tueur qu'il a lui-même sauvé enfant.",
  description_longue: "Le docteur Tenma voit sa vie basculer lorsqu'un de ses anciens patients devient un monstre sans âme. Une enquête psychologique glaçante sur la nature du mal.",
  image: "https://cdn.myanimelist.net/images/anime/102/200102.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/102/300102.jpg",
  chapitres: "162",
  date: "1994-12-05",
  statut: "Terminé",
  lien: "/monster",
  type: "Manga",
  genre: ["Psychologique", "Thriller", "Mystère", "Drame"]
},
{
  id: 92,
  titre: "Berserk",
  auteur: "Kentaro Miura",
  description: "Un mercenaire maudit affronte démons et destin dans un monde brutal.",
  description_longue: "Guts, guerrier marqué, lutte contre un monde où monstres et hommes se confondent. Sa quête sanglante mêle vengeance, amour perdu et combat contre le destin.",
  image: "https://cdn.myanimelist.net/images/anime/103/200103.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/103/300103.jpg",
  chapitres: "380+",
  date: "1989-08-25",
  statut: "En cours",
  lien: "/berserk",
  type: "Manga",
  genre: ["Dark Fantasy", "Action", "Drame", "Horreur"]
},
{
  id: 93,
  titre: "The Rising of the Shield Hero",
  auteur: "Aneko Yusagi",
  description: "Naofumi est invoqué dans un autre monde comme héros du bouclier.",
  description_longue: "Accusé à tort et rejeté, Naofumi doit survivre seul avec son bouclier. Sa chute devient le point de départ d'une reconstruction empreinte de force.",
  image: "https://cdn.myanimelist.net/images/anime/104/200104.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/104/300104.jpg",
  chapitres: "22+ volumes",
  date: "2013-08-22",
  statut: "En cours",
  lien: "/shield-hero",
  type: "Light Novel",
  genre: ["Isekai", "Aventure", "Fantasy", "Drame"]
},
{
  id: 94,
  titre: "Mushoku Tensei",
  auteur: "Rifujin na Magonote",
  description: "Un homme réincarné cherche à donner un vrai sens à sa nouvelle vie.",
  description_longue: "Après une vie d'échecs, un homme renaît en Rudeus Greyrat. Déterminé à ne plus gaspiller son existence, il poursuit la rédemption à travers magie et aventure.",
  image: "https://cdn.myanimelist.net/images/anime/105/200105.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/105/300105.jpg",
  chapitres: "26 volumes",
  date: "2014-01-23",
  statut: "Terminé",
  lien: "/mushoku-tensei",
  type: "Light Novel",
  genre: ["Isekai", "Fantasy", "Aventure", "Romance"]
},
{
  id: 95,
  titre: "Dr. Stone",
  auteur: "Riichiro Inagaki",
  description: "L'humanité se réveille dans un monde pétrifié, et la science devient l'arme de survie.",
  description_longue: "Des millénaires après une pétrification mystérieuse, Senku entreprend de reconstruire la civilisation. Un hommage à l'ingéniosité humaine défiant le temps.",
  image: "https://cdn.myanimelist.net/images/anime/106/200106.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/106/300106.jpg",
  chapitres: "232",
  date: "2017-03-06",
  statut: "Terminé",
  lien: "/dr-stone",
  type: "Manga",
  genre: ["Aventure", "Science-fiction", "Comédie", "Survie"]
},
{
  id: 96,
  titre: "The Promised Neverland",
  auteur: "Kaiu Shirai",
  description: "Des enfants découvrent la vérité terrifiante sur leur orphelinat.",
  description_longue: "Emma, Norman et Ray vivent heureux jusqu'à découvrir un secret impensable. Ils préparent une évasion risquée où intelligence et courage sont leurs seules armes.",
  image: "https://cdn.myanimelist.net/images/anime/107/200107.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/107/300107.jpg",
  chapitres: "181",
  date: "2016-08-01",
  statut: "Terminé",
  lien: "/the-promised-neverland",
  type: "Manga",
  genre: ["Thriller", "Mystère", "Drame", "Psychologique"]
},
{
  id: 97,
  titre: "Fire Force",
  auteur: "Atsushi Okubo",
  description: "Des pompiers spéciaux affrontent des humains transformés en flammes vivantes.",
  description_longue: "Shinra Kusakabe rejoint la Fire Force pour combattre les combustions humaines. Entre feu et foi, il découvre les secrets d'une société brûlante.",
  image: "https://cdn.myanimelist.net/images/anime/108/200108.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/108/300108.jpg",
  chapitres: "304",
  date: "2015-09-23",
  statut: "Terminé",
  lien: "/fire-force",
  type: "Manga",
  genre: ["Action", "Surnaturel", "Science-fiction", "Drame"]
},
{
  id: 98,
  titre: "Code Geass",
  auteur: "Ichiro Okouchi",
  description: "Un prince banni obtient un pouvoir qui lui permet de contrôler les autres.",
  description_longue: "Lelouch vi Britannia reçoit le 'Geass', pouvoir d'obéissance absolue. Masqué sous le nom de Zero, il déclare la guerre à un empire corrompu.",
  image: "https://cdn.myanimelist.net/images/anime/109/200109.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/109/300109.jpg",
  chapitres: "50 épisodes",
  date: "2006-10-05",
  statut: "Terminé",
  lien: "/code-geass",
  type: "Anime",
  genre: ["Action", "Mecha", "Psychologique", "Politique"]
},
{
  id: 99,
  titre: "Steins;Gate",
  auteur: "Chiyomaru Shikura",
  description: "Un groupe d'amis découvre comment envoyer des messages dans le passé.",
  description_longue: "Rintaro Okabe fait une découverte qui bouleverse le temps. Entre paradoxes et sacrifices, il lutte contre un futur qu'il a lui-même altéré.",
  image: "https://cdn.myanimelist.net/images/anime/110/200110.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/110/300110.jpg",
  chapitres: "24 épisodes",
  date: "2009-10-15",
  statut: "Terminé",
  lien: "/steins-gate",
  type: "Visual Novel",
  genre: ["Science-fiction", "Thriller", "Drame", "Romance"]
},
{
  id: 100,
  titre: "Tower of God",
  auteur: "SIU",
  description: "Un garçon gravit une tour où chaque étage promet un vœu exaucé.",
  description_longue: "Bam entre dans la Tour pour retrouver Rachel. Entre trahisons et épreuves, il découvre la vérité sur ce monde sans pitié.",
  image: "https://cdn.myanimelist.net/images/anime/111/200111.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/111/300111.jpg",
  chapitres: "590+",
  date: "2010-06-30",
  statut: "En cours",
  lien: "/tower-of-god",
  type: "Manhwa",
  genre: ["Fantasy", "Action", "Mystère", "Drame"]
},

{
  id: 101,
  titre: "Samurai Champloo",
  auteur: "Shinichiro Watanabe",
  description: "Deux samouraïs et une serveuse partent en quête d'un mystérieux guerrier au parfum de tournesol.",
  description_longue: "Dans un Japon alternatif mêlant hip-hop et sabre, Mugen et Jin, opposés en tout, se retrouvent liés par Fuu. Un road-trip rythmé par la liberté, la musique et la mélancolie des destins croisés.",
  image: "https://cdn.myanimelist.net/images/anime/112/200112.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/112/300112.jpg",
  chapitres: "26 épisodes",
  date: "2004-05-20",
  statut: "Terminé",
  lien: "/samurai-champloo",
  type: "Anime",
  genre: ["Action", "Aventure", "Historique", "Comédie", "Drame"]
},
{
  id: 102,
  titre: "Trigun",
  auteur: "Yasuhiro Nightow",
  description: "Un pistolero pacifiste est poursuivi pour une prime colossale sur sa tête.",
  description_longue: "Vash the Stampede traverse un monde désertique, prêchant la paix dans un univers violent. Entre humour et tragédie, il incarne l'espoir fragile d'un monde sans haine.",
  image: "https://cdn.myanimelist.net/images/anime/113/200113.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/113/300113.jpg",
  chapitres: "97",
  date: "1995-04-25",
  statut: "Terminé",
  lien: "/trigun",
  type: "Manga",
  genre: ["Action", "Science-fiction", "Western", "Drame", "Comédie"]
},
{
  id: 103,
  titre: "Cowboy Bebop",
  auteur: "Shinichiro Watanabe",
  description: "Une bande de chasseurs de primes parcourt l'espace à la recherche de leur passé.",
  description_longue: "Spike, Jet, Faye et Ed naviguent de planète en planète, fuyant la solitude sous des airs de jazz. Chaque mission devient une mélodie mélancolique sur la liberté et la perte.",
  image: "https://cdn.myanimelist.net/images/anime/114/200114.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/114/300114.jpg",
  chapitres: "26 épisodes",
  date: "1998-04-03",
  statut: "Terminé",
  lien: "/cowboy-bebop",
  type: "Anime",
  genre: ["Action", "Science-fiction", "Drame", "Noir", "Espace"]
},
{
  id: 104,
  titre: "Rurouni Kenshin",
  auteur: "Nobuhiro Watsuki",
  description: "Un ancien assassin cherche la rédemption dans un Japon en mutation.",
  description_longue: "Kenshin Himura, autrefois tueur sans pitié, manie désormais un sabre à lame inversée pour protéger les innocents. Une fresque sur la culpabilité, la justice et la paix intérieure.",
  image: "https://cdn.myanimelist.net/images/anime/115/200115.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/115/300115.jpg",
  chapitres: "255",
  date: "1994-04-04",
  statut: "Terminé",
  lien: "/rurouni-kenshin",
  type: "Manga",
  genre: ["Action", "Historique", "Romance", "Drame", "Aventure"]
},
{
  id: 105,
  titre: "Elfen Lied",
  auteur: "Lynn Okamoto",
  description: "Une fille aux pouvoirs meurtriers échappe d'un laboratoire secret.",
  description_longue: "Lucy, mutante dotée de bras invisibles, erre entre innocence et carnage. Derrière la violence se cache une réflexion sur l'abandon, la douleur et la soif d'amour.",
  image: "https://cdn.myanimelist.net/images/anime/116/200116.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/116/300116.jpg",
  chapitres: "107",
  date: "2002-06-06",
  statut: "Terminé",
  lien: "/elfen-lied",
  type: "Manga",
  genre: ["Horreur", "Psychologique", "Drame", "Romance", "Science-fiction"]
},
{
  id: 106,
  titre: "Dororo",
  auteur: "Osamu Tezuka",
  description: "Un jeune samouraï part reconquérir les parties de son corps volées par des démons.",
  description_longue: "Hyakkimaru, né sans membres, sillonne le Japon féodal en quête de son humanité. Avec Dororo, il affronte des monstres extérieurs et intérieurs dans un voyage tragique.",
  image: "https://cdn.myanimelist.net/images/anime/117/200117.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/117/300117.jpg",
  chapitres: "48",
  date: "1967-08-09",
  statut: "Terminé",
  lien: "/dororo",
  type: "Manga",
  genre: ["Action", "Aventure", "Historique", "Surnaturel", "Drame"]
},
{
  id: 107,
  titre: "Fruits Basket",
  auteur: "Natsuki Takaya",
  description: "Une fille découvre une famille maudite se transformant en animaux du zodiaque.",
  description_longue: "Tohru Honda, optimiste et douce, apaise les blessures des Soma. Sous ses airs de conte, une histoire profonde sur la guérison, la honte et l'amour inconditionnel.",
  image: "https://cdn.myanimelist.net/images/anime/118/200118.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/118/300118.jpg",
  chapitres: "136",
  date: "1998-07-18",
  statut: "Terminé",
  lien: "/fruits-basket",
  type: "Manga",
  genre: ["Romance", "Drame", "Fantastique", "Comédie", "Slice of Life"]
},
{
  id: 108,
  titre: "Kimi ni Todoke",
  auteur: "Karuho Shiina",
  description: "Une lycéenne timide découvre l'amitié et l'amour pour la première fois.",
  description_longue: "Sawako, surnommée Sadako à cause de son air effrayant, apprend à se rapprocher des autres. Une romance douce et réaliste sur la peur du rejet et la beauté de la sincérité.",
  image: "https://cdn.myanimelist.net/images/anime/119/200119.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/119/300119.jpg",
  chapitres: "123",
  date: "2005-12-13",
  statut: "Terminé",
  lien: "/kimi-ni-todoke",
  type: "Manga",
  genre: ["Romance", "Comédie", "Slice of Life", "Scolaire", "Drame"]
},
{
  id: 109,
  titre: "Parasyte",
  auteur: "Hitoshi Iwaaki",
  description: "Un lycéen devient l'hôte d'un parasite extraterrestre et lutte pour son humanité.",
  description_longue: "Shinichi vit une cohabitation forcée avec Migi, un parasite ayant pris possession de sa main. Ensemble, ils affrontent d'autres créatures voraces, cherchant un équilibre fragile entre instinct et morale.",
  image: "https://cdn.myanimelist.net/images/anime/120/200120.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/120/300120.jpg",
  chapitres: "64",
  date: "1988-10-22",
  statut: "Terminé",
  lien: "/parasyte",
  type: "Manga",
  genre: ["Horreur", "Science-fiction", "Psychologique", "Action", "Drame"]
},
{
  id: 110,
  titre: "Grimgar of Fantasy and Ash",
  auteur: "Ao Jyumonji",
  description: "Un groupe d'étrangers se réveille sans souvenirs dans un monde inconnu.",
  description_longue: "Perdus et vulnérables, Haruhiro et ses compagnons doivent apprendre à survivre dans un monde où chaque combat est une lutte réelle. Un récit poétique sur la peur, la perte et la solidarité.",
  image: "https://cdn.myanimelist.net/images/anime/121/200121.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/121/300121.jpg",
  chapitres: "18+ volumes",
  date: "2013-06-25",
  statut: "En cours",
  lien: "/grimgar",
  type: "Light Novel",
  genre: ["Fantasy", "Aventure", "Drame", "Isekai", "Psychologique"]
},
 {
  id: 111,
  titre: "No Game No Life",
  auteur: "Yuu Kamiya",
  description: "Deux génies du jeu sont transportés dans un monde où tout se décide par des paris.",
  description_longue: "Sora et Shiro, duo inséparable de gamers, affrontent dieux et nations dans des parties d'esprit et de stratégie. Leur but : conquérir un monde où la logique est plus forte que la guerre.",
  image: "https://cdn.myanimelist.net/images/anime/122/200122.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/122/300122.jpg",
  chapitres: "12 volumes",
  date: "2012-04-25",
  statut: "En pause",
  lien: "/no-game-no-life",
  type: "Light Novel",
  genre: ["Fantasy", "Comédie", "Isekai", "Psychologique"]
},
{
  id: 112,
  titre: "That Time I Got Reincarnated as a Slime",
  auteur: "Fuse",
  description: "Un homme meurt et renaît dans un autre monde sous la forme d'un slime.",
  description_longue: "Rimuru Tempest, créature gélatineuse dotée d'un cœur humain, bâtit un royaume de monstres unis. Une aventure d'humour, de sagesse et de diplomatie dans un monde magique éclatant.",
  image: "https://cdn.myanimelist.net/images/anime/123/200123.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/123/300123.jpg",
  chapitres: "19+ volumes",
  date: "2013-02-20",
  statut: "En cours",
  lien: "/slime",
  type: "Light Novel",
  genre: ["Isekai", "Fantasy", "Aventure", "Action"]
},
{
  id: 113,
  titre: "The Ancient Magus' Bride",
  auteur: "Kore Yamazaki",
  description: "Une jeune fille vendue devient l'apprentie d'un magicien inhumain.",
  description_longue: "Chise, rejetée depuis toujours, découvre un monde féérique et cruel auprès d'Elias, un mage énigmatique. Leur lien entre humanité et magie redonne sens à la beauté et à la peur du monde.",
  image: "https://cdn.myanimelist.net/images/anime/124/200124.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/124/300124.jpg",
  chapitres: "100+",
  date: "2013-11-30",
  statut: "En cours",
  lien: "/ancient-magus-bride",
  type: "Manga",
  genre: ["Fantasy", "Romance", "Surnaturel", "Drame"]
},
{
  id: 114,
  titre: "Death Parade",
  auteur: "Yuzuru Tachikawa",
  description: "Les âmes des morts sont jugées à travers des jeux cruels.",
  description_longue: "Dans un bar où la mort est un spectacle, Decim observe la vraie nature humaine. À travers chaque partie, la série interroge le sens du jugement, de la vie et de la rédemption.",
  image: "https://cdn.myanimelist.net/images/anime/125/200125.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/125/300125.jpg",
  chapitres: "12 épisodes",
  date: "2015-01-09",
  statut: "Terminé",
  lien: "/death-parade",
  type: "Anime",
  genre: ["Psychologique", "Drame", "Mystère", "Surnaturel"]
},
{
  id: 115,
  titre: "Psycho-Pass",
  auteur: "Gen Urobuchi",
  description: "Dans un futur contrôlé par une IA, la criminalité est mesurée avant d'exister.",
  description_longue: "Akane Tsunemori découvre un système qui juge les intentions avant les actes. Entre justice, peur et libre arbitre, elle affronte un monde où penser peut déjà être un crime.",
  image: "https://cdn.myanimelist.net/images/anime/126/200126.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/126/300126.jpg",
  chapitres: "41 épisodes",
  date: "2012-10-12",
  statut: "En cours",
  lien: "/psycho-pass",
  type: "Anime",
  genre: ["Science-Fiction", "Thriller", "Psychologique", "Action"]
},
{
  id: 116,
  titre: "Erased",
  auteur: "Kei Sanbe",
  description: "Un homme retourne dans son enfance pour empêcher un meurtre.",
  description_longue: "Satoru, doté d'un pouvoir de retour temporel, revit son passé pour sauver une camarade disparue. Un thriller bouleversant sur la culpabilité, le courage et la seconde chance.",
  image: "https://cdn.myanimelist.net/images/anime/127/200127.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/127/300127.jpg",
  chapitres: "44",
  date: "2012-06-04",
  statut: "Terminé",
  lien: "/erased",
  type: "Manga",
  genre: ["Mystère", "Thriller", "Drame", "Psychologique"]
},
{
  id: 117,
  titre: "Paranoia Agent",
  auteur: "Satoshi Kon",
  description: "Une série d'agressions mystérieuses plonge la ville dans la psychose.",
  description_longue: "Un adolescent à la batte dorée sème la panique. Mais derrière les rumeurs se cachent mensonges, peurs et vérités collectives. Une critique acide de la société moderne.",
  image: "https://cdn.myanimelist.net/images/anime/128/200128.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/128/300128.jpg",
  chapitres: "13 épisodes",
  date: "2004-02-02",
  statut: "Terminé",
  lien: "/paranoia-agent",
  type: "Anime",
  genre: ["Psychologique", "Mystère", "Drame", "Surréaliste"]
},
{
  id: 118,
  titre: "Terror in Resonance",
  auteur: "Shinichiro Watanabe",
  description: "Deux jeunes terroristes défient le gouvernement pour révéler un secret.",
  description_longue: "Nine et Twelve, génies fuyant un passé d'expérimentations, orchestrent des attentats énigmatiques. Une œuvre poignante où la justice et la vengeance s'entremêlent dans un cri silencieux.",
  image: "https://cdn.myanimelist.net/images/anime/129/200129.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/129/300129.jpg",
  chapitres: "11 épisodes",
  date: "2014-07-10",
  statut: "Terminé",
  lien: "/terror-in-resonance",
  type: "Anime",
  genre: ["Thriller", "Psychologique", "Drame", "Mystère"]
},
{
  id: 119,
  titre: "91 Days",
  auteur: "Hiro Kaburagi",
  description: "Un homme infiltre la mafia pour venger le meurtre de sa famille.",
  description_longue: "Dans l'Amérique de la Prohibition, Angelo revêt le masque de la vengeance. Entre loyauté et trahison, il découvre que la haine consume autant qu'elle libère.",
  image: "https://cdn.myanimelist.net/images/anime/130/200130.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/130/300130.jpg",
  chapitres: "12 épisodes",
  date: "2016-07-09",
  statut: "Terminé",
  lien: "/91-days",
  type: "Anime",
  genre: ["Drame", "Crime", "Thriller", "Action"]
},
{
  id: 120,
  titre: "Black Lagoon",
  auteur: "Rei Hiroe",
  description: "Un employé kidnappé devient mercenaire dans le monde du crime.",
  description_longue: "Rokurou, simple salarié, découvre la brutalité du monde à travers le Lagoon Company. Entre fusillades, philosophie et chaos, il choisit de vivre sans retour possible.",
  image: "https://cdn.myanimelist.net/images/anime/131/200131.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/131/300131.jpg",
  chapitres: "120+",
  date: "2002-04-19",
  statut: "En cours",
  lien: "/black-lagoon",
  type: "Manga",
  genre: ["Action", "Crime", "Drame", "Psychologique"]
},
 {
  id: 121,
  titre: "Yu Yu Hakusho",
  auteur: "Yoshihiro Togashi",
  description: "Un voyou devient détective spirituel après un acte héroïque.",
  description_longue: "Yusuke Urameshi, adolescent rebelle, meurt en sauvant un enfant. Ressuscité par le monde des esprits, il enquête sur les forces surnaturelles qui menacent l'humanité.",
  image: "https://cdn.myanimelist.net/images/anime/132/200132.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/132/300132.jpg",
  chapitres: "175",
  date: "1990-12-03",
  statut: "Terminé",
  lien: "/yu-yu-hakusho",
  type: "Manga",
  genre: ["Action", "Aventure", "Surnaturel", "Combat", "Shōnen"]
},
{
  id: 122,
  titre: "Claymore",
  auteur: "Norihiro Yagi",
  description: "Des guerrières mi-humaines affrontent des monstres qui menacent l'humanité.",
  description_longue: "Clare, une Claymore, combat des créatures dévoreuses d'humains tout en cherchant vengeance contre celle qui a détruit sa vie. Sa route est pavée de douleur, d'honneur et d'un espoir presque éteint.",
  image: "https://cdn.myanimelist.net/images/anime/133/200133.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/133/300133.jpg",
  chapitres: "155",
  date: "2001-05-06",
  statut: "Terminé",
  lien: "/claymore",
  type: "Manga",
  genre: ["Action", "Dark Fantasy", "Drame", "Surnaturel"]
},
{
  id: 123,
  titre: "Blue Exorcist",
  auteur: "Kazue Kato",
  description: "Un adolescent découvre qu'il est le fils du diable et veut devenir exorciste.",
  description_longue: "Rin Okumura apprend qu'il porte en lui le pouvoir de Satan. Décidé à le combattre plutôt qu'à l'accepter, il rejoint l'académie des exorcistes pour protéger ceux qu'il aime d'un monde qui le rejette.",
  image: "https://cdn.myanimelist.net/images/anime/134/200134.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/134/300134.jpg",
  chapitres: "150+",
  date: "2009-04-04",
  statut: "En cours",
  lien: "/blue-exorcist",
  type: "Manga",
  genre: ["Action", "Surnaturel", "Fantasy", "Shōnen"]
},
{
  id: 124,
  titre: "Soul Eater",
  auteur: "Atsushi Okubo",
  description: "Des élèves d'une académie collectent des âmes pour forger des armes vivantes.",
  description_longue: "Dans la Death Weapon Meister Academy, des duos singuliers chassent les âmes corrompues pour maintenir l'équilibre du monde. Entre style gothique, humour et combat, chaque coup de faux forge le destin.",
  image: "https://cdn.myanimelist.net/images/anime/135/200135.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/135/300135.jpg",
  chapitres: "113",
  date: "2004-05-12",
  statut: "Terminé",
  lien: "/soul-eater",
  type: "Manga",
  genre: ["Action", "Fantasy", "Comédie", "Surnaturel", "Scolaire"]
},
{
  id: 125,
  titre: "Assassination Classroom",
  auteur: "Yusei Matsui",
  description: "Une classe doit assassiner son professeur avant qu'il ne détruise la Terre.",
  description_longue: "Koro-sensei, une créature jaune surpuissante, devient l'enseignant d'élèves exclus. Il leur apprend non seulement à tuer, mais surtout à vivre, dans une leçon d'humanité pleine de rires et de larmes.",
  image: "https://cdn.myanimelist.net/images/anime/136/200136.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/136/300136.jpg",
  chapitres: "180",
  date: "2012-07-02",
  statut: "Terminé",
  lien: "/assassination-classroom",
  type: "Manga",
  genre: ["Comédie", "Action", "Scolaire", "Drame", "Shōnen"]
},
{
  id: 126,
  titre: "Toradora!",
  auteur: "Yuyuko Takemiya",
  description: "Deux lycéens aux caractères opposés s'allient pour aider l'autre en amour.",
  description_longue: "Ryuuji, calme mais mal compris, et Taiga, petite mais redoutable, forment un duo improbable. Leur alliance maladroite se transforme peu à peu en une histoire sincère de compréhension et d'amour.",
  image: "https://cdn.myanimelist.net/images/anime/137/200137.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/137/300137.jpg",
  chapitres: "10 volumes",
  date: "2006-03-10",
  statut: "Terminé",
  lien: "/toradora",
  type: "Light Novel",
  genre: ["Romance", "Comédie", "Slice of Life", "Scolaire"]
},
{
  id: 127,
  titre: "Vivy: Fluorite Eye's Song",
  auteur: "Tappei Nagatsuki",
  description: "Une IA chanteuse lutte pour sauver l'humanité d'un futur apocalyptique.",
  description_longue: "Vivy, première IA artiste, découvre la douleur et la beauté de la conscience à travers la musique et la guerre. Une épopée émotionnelle mêlant science-fiction et poésie.",
  image: "https://cdn.myanimelist.net/images/anime/138/200138.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/138/300138.jpg",
  chapitres: "13 épisodes",
  date: "2021-04-03",
  statut: "Terminé",
  lien: "/vivy-fluorite-eyes-song",
  type: "Anime",
  genre: ["Science-Fiction", "Drame", "Musique", "Action", "Psychologique"]
},
{
  id: 128,
  titre: "Sword Art Online",
  auteur: "Reki Kawahara",
  description: "Des joueurs piégés dans un jeu en ligne doivent y survivre pour en sortir.",
  description_longue: "Kirito, expert en réalité virtuelle, doit survivre dans un MMORPG mortel où la défaite signifie la mort réelle. Entre amour et combat, il redéfinit les limites entre jeu et vie.",
  image: "https://cdn.myanimelist.net/images/anime/139/200139.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/139/300139.jpg",
  chapitres: "27+ volumes",
  date: "2009-04-10",
  statut: "En cours",
  lien: "/sword-art-online",
  type: "Light Novel",
  genre: ["Action", "Aventure", "Romance", "Fantasy", "Isekai", "Science-Fiction"]
},
{
  id: 129,
  titre: "Log Horizon",
  auteur: "Mamare Touno",
  description: "Des joueurs coincés dans un MMORPG doivent créer une nouvelle société.",
  description_longue: "Shiroe, stratège taciturne, réunit les joueurs perdus pour bâtir un monde organisé au-delà du simple jeu. Une réflexion subtile sur la communauté, la stratégie et l'identité virtuelle.",
  image: "https://cdn.myanimelist.net/images/anime/140/200140.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/140/300140.jpg",
  chapitres: "14 volumes",
  date: "2010-05-01",
  statut: "En cours",
  lien: "/log-horizon",
  type: "Light Novel",
  genre: ["Isekai", "Fantasy", "Aventure", "Stratégie", "Science-Fiction"]
},
{
  id: 130,
  titre: "Ergo Proxy",
  auteur: "Dai Sato",
  description: "Dans une cité sous dôme, une enquêtrice découvre la vérité sur les humains et les androïdes.",
  description_longue: "Re-l Mayer, agent d'élite, affronte des entités appelées 'Proxys' dans une quête existentielle. Entre philosophie et science-fiction, l'anime explore ce qu'être humain signifie vraiment.",
  image: "https://cdn.myanimelist.net/images/anime/141/200141.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/141/300141.jpg",
  chapitres: "23 épisodes",
  date: "2006-02-25",
  statut: "Terminé",
  lien: "/ergo-proxy",
  type: "Anime",
  genre: ["Science-Fiction", "Psychologique", "Philosophique", "Mystère", "Drame"]
},
 {
  id: 131,
  titre: "Hell's Paradise",
  auteur: "Yuji Kaku",
  description: "Un assassin immortel est envoyé sur une île remplie de créatures monstrueuses.",
  description_longue: "Gabimaru cherche la vie éternelle sur une terre maudite où tout respire la mort. Violence et beauté s'y mêlent dans une fable sur le pardon et le désir de vivre.",
  image: "https://cdn.myanimelist.net/images/anime/142/200142.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/142/300142.jpg",
  chapitres: "127",
  date: "2018-01-22",
  statut: "Terminé",
  lien: "/hells-paradise",
  type: "Manga",
  genre: ["Action", "Dark Fantasy", "Drame", "Surnaturel", "Psychologique"]
},
{
  id: 132,
  titre: "Oshi no Ko",
  auteur: "Aka Akasaka",
  description: "Deux fans renaissent en enfants d'une idole qu'ils admiraient.",
  description_longue: "Dans les coulisses du show-business, vérité et mensonge s'entremêlent. Loin du rêve doré, c'est une tragédie moderne sur l'identité, la vengeance et la lumière trompeuse de la célébrité.",
  image: "https://cdn.myanimelist.net/images/anime/143/200143.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/143/300143.jpg",
  chapitres: "160+",
  date: "2020-04-23",
  statut: "En cours",
  lien: "/oshi-no-ko",
  type: "Manga",
  genre: ["Drame", "Mystère", "Psychologique", "Idole", "Société"]
},
{
  id: 133,
  titre: "Beastars",
  auteur: "Paru Itagaki",
  description: "Dans une école d'animaux anthropomorphes, un loup lutte contre ses instincts.",
  description_longue: "Legoshi, doux par nature mais carnivore de naissance, découvre les nuances entre faim et amour. Une parabole sur la société, les désirs et la peur de soi-même.",
  image: "https://cdn.myanimelist.net/images/anime/144/200144.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/144/300144.jpg",
  chapitres: "196",
  date: "2016-09-08",
  statut: "Terminé",
  lien: "/beastars",
  type: "Manga",
  genre: ["Drame", "Psychologique", "Romance", "Société", "Anthropomorphisme"]
},
{
  id: 134,
  titre: "Land of the Lustrous",
  auteur: "Haruko Ichikawa",
  description: "Des êtres faits de gemmes combattent des créatures venues de la Lune.",
  description_longue: "Phos, la plus fragile des gemmes, cherche un sens à son existence. Un conte visuel unique, mêlant philosophie, solitude et métamorphose éternelle.",
  image: "https://cdn.myanimelist.net/images/anime/145/200145.jpg",
  iconImage: "https://cdn.myanimelist.net/images/characters/145/300145.jpg",
  chapitres: "108",
  date: "2012-10-25",
  statut: "En cours",
  lien: "/land-of-the-lustrous",
  type: "Manga",
  genre: ["Philosophique", "Science-Fiction", "Drame", "Fantastique", "Existentialisme"]
},
{
  id: 135,
  titre: "Magi: The Labyrinth of Magic",
  auteur: "Shinobu Ohtaka",
  description: "Un jeune aventurier explore des donjons mystérieux remplis de trésors et de magie.",
  description_longue: "Aladdin, accompagné d'Ali Baba et Morgiana, parcourt un monde inspiré des contes des Mille et Une Nuits. Entre liberté, pouvoir et destin, leur voyage révèle la lumière et l'ombre de l'humanité.",
  image: "https://cdn.myanimelist.net/images/anime/146/200146.jpg",
  iconImage: "",
  chapitres: "~369",
  date: "2009-06-03",
  statut: "Terminé",
  lien: "/magi",
  type: "Anime",
  genre: ["Aventure", "Fantasy", "Action", "Magie", "Shōnen"]
},
{
  id: 136,
  titre: "To Your Eternity",
  auteur: "Yoshitoki Ōima",
  description: "Un être immortel découvre les émotions humaines à travers les vies qu’il croise.",
  description_longue: "Fushi, entité changeante, apprend la douleur, la perte et l’amour au contact des hommes. Une fable mélancolique sur la mémoire et le sens de l’existence.",
  image: "",
  iconImage: "",
  chapitres: "~200",
  date: "2016-11-09",
  statut: "En cours",
  lien: "/to-your-eternity",
  type: "Anime",
  genre: ["Drame", "Fantasy", "Philosophique", "Aventure", "Psychologique"]
},
{
  id: 137,
  titre: "Jobless Oblivion",
  auteur: "Hwan Shin",
  description: "Un héros oublié revient dans le monde des vivants pour se venger des dieux.",
  description_longue: "Abandonné par tous, il forge sa propre destinée à travers la haine et la volonté. Un manhwa sombre sur le prix de la puissance et la solitude du survivant.",
  image: "",
  iconImage: "",
  chapitres: "~95",
  date: "2021-03-17",
  statut: "En cours",
  lien: "/jobless-oblivion",
  type: "Manhwa",
  genre: ["Action", "Dark Fantasy", "Vengeance", "Surnaturel", "Drame"]
},
{
  id: 138,
  titre: "Noblesse",
  auteur: "Son Jeho",
  description: "Un vampire noble se réveille après 800 ans de sommeil dans un monde moderne.",
  description_longue: "Cadis Etrama di Raizel, être immortel, protège les humains des organisations secrètes. Un mélange d’action, d’humour et de loyauté éternelle.",
  image: "",
  iconImage: "",
  chapitres: "~544",
  date: "2007-12-30",
  statut: "Terminé",
  lien: "/noblesse",
  type: "Anime",
  genre: ["Action", "Surnaturel", "Vampire", "Comédie", "École"]
},
{
  id: 139,
  titre: "The Beginning After the End",
  auteur: "TurtleMe",
  description: "Un roi se réincarne dans un monde magique pour vivre une seconde vie.",
  description_longue: "Arthur Leywin, ancien souverain, renaît en enfant doté d’un talent immense. Une épopée mêlant aventure, tragédie et renaissance spirituelle.",
  image: "",
  iconImage: "",
  chapitres: "~190",
  date: "2018-07-07",
  statut: "En cours",
  lien: "/the-beginning-after-the-end",
  type: "Manhwa",
  genre: ["Fantasy", "Aventure", "Action", "Isekai", "Drame"]
},
{
  id: 140,
  titre: "Eleceed",
  auteur: "Son Jeho",
  description: "Un jeune homme et son chat éveillent des pouvoirs surnaturels pour protéger les autres.",
  description_longue: "Jiwoo, rapide comme l’éclair, apprend à maîtriser sa force sous la tutelle d’un chat doté de conscience. Une aventure fun et bienveillante, pleine d’action et de cœur.",
  image: "",
  iconImage: "",
  chapitres: "~300",
  date: "2018-10-02",
  statut: "En cours",
  lien: "/eleceed",
  type: "Manhwa",
  genre: ["Action", "Comédie", "Surnaturel", "Amitié", "Héros"]
},
{
  id: 141,
  titre: "Lookism",
  auteur: "Park Tae-jun",
  description: "Un adolescent se réveille dans un nouveau corps, beau et charismatique.",
  description_longue: "Park Hyung-suk découvre la superficialité du monde en alternant entre deux corps. Une critique sociale mordante sur l’apparence et la dignité humaine.",
  image: "",
  iconImage: "",
  chapitres: "~470",
  date: "2014-11-20",
  statut: "En cours",
  lien: "/lookism",
  type: "Anime",
  genre: ["Drame", "Comédie", "Société", "Psychologique", "Vie scolaire"]
},
{
  id: 142,
  titre: "Weak Hero",
  auteur: "Seopas",
  description: "Un étudiant frêle affronte les brutes avec intelligence et détermination.",
  description_longue: "Gray, petit mais rusé, transforme chaque combat en stratégie. Un manhwa de survie urbaine où le courage l’emporte sur la force brute.",
  image: "",
  iconImage: "",
  chapitres: "~260",
  date: "2018-05-06",
  statut: "En cours",
  lien: "/weak-hero",
  type: "Manhwa",
  genre: ["Action", "Drame", "Scolaire", "Psychologique", "Combat de rue"]
}
]